### ISSUE TITLE
Patching replaces full lists

### ISSUE THREAD

**Issue by samabbey-sonocent** [pikaju/dart-json-patch#2]
Hi,

I am trying to use this package and encountered an issue with adding objects to lists. The patches created replace the full list every time rather than adding to it.

I understand that this is intentional functionality at the moment (`// Always replace lists if the size changed (not optimal).`) Is this something that you are looking to fix/implement? It is stated functionality of [JSON Patch](https://tools.ietf.org/html/rfc6902) and means that patches aren't portable between platforms.

Many thanks,

Sam

**Comment by pikaju** [comment]
Hey, what exactly do you mean with "It is stated functionality of JSON Patch and means that patches aren't portable between platforms."? I'm unfortunately a bit short on time at the moment, pull requests are always welcome.

**Comment by samabbey-sonocent** [comment]
Hi, thanks for getting back to me! Sorry if I explained myself badly, my main problem is that I am wanting to store patches and this issue means that they can get quite large quite quickly! I will get a PR up for it this week,

Cheers,

Sam

**Comment by samabbey-sonocent** [comment]
I've put up #3 to fix this issue,

Thanks,
Sam

**Comment by pikaju** [comment]
Fixed in #3.
