### ISSUE TITLE
update to null-safety

### ISSUE THREAD

**Issue by torbenkeller** [pikaju/dart-json-patch#5]

**Comment by alexshikov** [comment]
Would be nice to have

**Comment by justkawal** [comment]
Migration to null-safety is done and tested fully.
Until the pull-request is merged by the owner of this **awesome package**
Use null-safe version of json-patch by this in your pubspec.yaml:

```
json_patch:
    git:
      url: https://github.com/justkawal/dart-json-patch.git

```
