### ISSUE TITLE
Copy and Move operations don't conform to the specification

### ISSUE THREAD

**Issue by Sam-Ford** [pikaju/dart-json-patch#8]
Copy and Move operations accept a 'to' parameter when in the specification the 'path' parameter is used for this purpose.

https://tools.ietf.org/html/rfc6902#section-4.4
http://jsonpatch.com/#copy

An exception is thrown when copy or move is called with correct parameters due to it not having a 'to' parameter

**Comment by Sam-Ford** [comment]
PR for this issue: https://github.com/pikaju/dart-json-patch/pull/7

**Comment by pikaju** [comment]
Merged. Thanks again!
